version: '2.2'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dev-api-whatsapp-crm:0.0.1
    env_file:
      - dev.env
    ports:
     - "3008:3008"
    container_name: dev-api-crm-whats
    working_dir: /app
    restart: always
    volumes:
        - .:/app
    expose:
      - "3008"
 